### ISSUE TITLE
The https://www.openvehicles.com/node/add/support-ticket page tell the user to download firmware 3.1 instead of recent stable

### ISSUE THREAD

**Issue by fowi4hjte** [openvehicles/Open-Vehicle-Monitoring-System-3#992] opened 2024-03-27 20:27 UTC
When you login on https://www.openvehicles.com you are at the user page. On the bottom there is the link to "Create new ticket" and when you press it, you get to https://www.openvehicles.com/node/add/support-ticket . This page seems to not be updated for a long time. Also the firmware file there seems to be version 3.1 . Its just 3,2MB big like other 3.1 firmware images. Current firmware images from 3.3 branch are 3,5MB big.

**Comment by markwj** [comment] 2024-03-28 00:28
The content of the page seems valid and good up-to-date guidance to me. There was one mention to v3.1 on the page, and I have updated that to remove the version reference completely.

Regarding the linked firmware file:

http://api.openvehicles.com/firmware/ota/v3.1/main/ovms3.bin

that downloads an ovms3.bin file with size 3.3MB (3,406,928 bytes) and md5 cffd06fb286d8eb8fad6b540b4a259bd (sha256 5d3972e5d82a3657e2967fe2cb62e2303146344172f51d4f4126a6fc3dcf0e78).

I checked that and it is identical to the current MAIN ovms3.bin with the same file size and checksum.

I am not sure where you get 3.2MB from? Note that there are more recent bigger firmware versions in EDGE (and with 3.3.004 just released to EAP), and those are 3.6MB in size - but they haven't been released as the 'main' tag version yet.

**Closed by markwj** 2024-03-28 00:28 UTC

**Comment by fowi4hjte** [comment] 2024-03-28 01:09
> The content of the page seems valid and good up-to-date guidance to me. There was one mention to v3.1 on the page, and I have updated that to remove the version reference completely.
> 
> Regarding the linked firmware file:
> 
> http://api.openvehicles.com/firmware/ota/v3.1/main/ovms3.bin

I can explain easy why i was expecting to get version 3.1 instead of any recent version 3.3:

When i use a link looking like this 
http://api.openvehicles.com/firmware/ota/v3.1 <- i get version 3.1.

If the link would look like this
http://api.openvehicles.com/firmware/ota/v3.3 <- i get version 3.3

About the possible existing OVMS versions i learned from here: https://ovms.dexters-web.de/firmware/ota/
Of course i pressed on the directory with the highest number and this is 3.3 .

With this first OVMS versioning experience and being new to OVMS, i visited https://www.openvehicles.com/node/add/support-ticket and have seen the link with the old version in the link. Because the file have no detailed version in its name the only expectationpoint to know what version i would get by using this link was the link itself and this say 3.1 and not 3.3.

**Comment by markwj** [comment] 2024-03-28 01:15
The problem is maintenance. If every time we release a new version we have to go and change 100 places where it is mentioned, that creates a huge amount of work for a project with zero paid or full time staff.

The 3.1 is in reference to the base version (v3.1 was the first version release for 3.x hardware as 3.0 was based on WROOM not WROVER, and never released). The link provided will retrieve the correct latest version. In fact, you should be able to use v3.1, v3.2, v3.3, or in future perhaps v3.4, in the URL path - they will all lead to the current v3.x version.

**Comment by fowi4hjte** [comment] 2024-03-28 02:02
Many projects have the same idea. Having a directory where the ready build images are pushed to and having such a link that never changes but the file always is been changed (proven by different checksums) to the latest pretested stable version but having all the time the same file name.

Here one example: 
Build results of stable version: https://f-droid.org/en/packages/org.fdroid.fdroid/
And the link to the stable tested release you can even remember and type based on your remembering into a browser:
https://f-droid.org/F-Droid.apk

Second example:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git
Its always the latest version.

Third example:
Symlinks on servers where you can download a linux iso file where the iso is named "latest.iso" or something like this.

Maybe when you have to rename it at some point once again, just use links like example
1. http://api.openvehicles.com/firmware/ota/main/ovms3.bin
2. http://dl.openvehicles.com/main/ovms3.bin
3. And other possible examples

The filename itself is telling already the firmware is for the ovms3 version.
I can put myself into a technical mindset and now after knowing that there was a different v3.0 but its hardware never got released i can understand that you named directory v3.1 because from this version onwards its the WROVER. 
But from user practical point of view: Do user have version 3.0? No, it was not released. So the ovms3.bin would be flashed on ovms3 hardware 3.1 and onwards that is capable to run osms3.bin because the people cant have the unreleased version 3.0 .
